# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1


[[main]]
  name = "Resources"
  identifier = "resources"
  url = ""
  weight = 2


[[main]]
  name = "Become a Google Ads Expert"
  parent = "resources"
  url = "post/ads"
  weight = 1

[[main]]
  name = "Hugo Add Table of Contents"
  parent = "resources"
  url = "post/Hugo-Table-Of-Contents"
  weight = 2
[[main]]
  name = "Java learning"
  parent = "resources"
  url = "post/Java"
  weight = 3

[[main]]
  name = "Data Structure"
  parent = "resources"
  url = "post/data_structure"
  weight = 4

[[main]]
  name = "Graph in Computer Science"
  parent = "resources"
  url = "post/graph"
  weight = 5
[[main]]
  name = "Tree in Computer Science"
  parent = "resources"
  url = "post/tree"
  weight = 6
[[main]]
  name = "Computer Architecture"
  parent = "resources"
  url = "post/computer_architecture"
  weight = 7

[[main]]
  name = "Competitive Programming"
  parent = "resources"
  url = "post/competitive_programming"
  weight = 8




[[main]]
  name = "My Projects"
  url = "#about"
  weight = 3

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 4
